module.exports = {
    accum: require('./src/_accum'),
    allPass: require('./src/_allPass'),
    alterProp: require('./src/_alterProp'),
    concat: require('./src/_concat'),
    curry: require('./src/_curry'),
    filter: require('./src/_filter'),
    flatMap: require('./src/_flatMap'),
    flatten: require('./src/_flatten'),
    isIn: require('./src/_isIn'),
    majority: require('./src/_majority'),
    majorityPass: require('./src/_majorityPass'),
    map: require('./src/_map'),
    mergeAllBy: require('./src/_mergeAllBy'),
    nPass: require('./src/_nPass'),
    pipe: require('./src/_pipe'),
    prop: require('./src/_prop'),
    reduce: require('./src/_reduce'),
    reduceWhile: require('./src/_reduceWhile'),
    swapIndex: require('./src/_swapIndex'),
    tail: require('./src/_tail'),
    uniq: require('./src/_uniq'),
    values: require('./src/_values'),
    zipObjBy: require('./src/_zipObjBy'),
    zipBy: require('./src/_zipBy')
};
